Fix: Style jsx error
The error `src/components/hero-section-6.tsx(10,20): error TS2322: Type '{ children: string; jsx: true; }' is not assignable to type 'DetailedHTMLProps<StyleHTMLAttributes<HTMLStyleElement>, HTMLStyleElement>'.` indicates an issue with how the `<style jsx>` tag is being used.  This commit will address the error.